import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/common/Layout'
const Home: NextPage = () => {
  return (
    <Layout title='TITLE'>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>HELLO CSEFLIX</h1>
        <h2>Content Section</h2>
      </div>
    </Layout>
  )
}

export default Home
